site_name: "D4rkC4rl's Blog"
site_description: 'There is the cyber blog of D4rkC4rl.'
site_url: https://fabrice000.github.io/D4rkC4rl/
use_directory_urls: true
nav:
  - Home: index.md
  - Notes:
      - Linux userful commands: notes/linux-essentials.md
      - Reconnaissance: notes/recon.md
  - Write-ups:
      - CTFs: 
          - SADC: 
              - "Overview": "writeups/SADC_NextGenCyber_CTF/index.md"
              - "Web":      "writeups/SADC_NextGenCyber_CTF/web.md"
              - "OSINT":    "writeups/SADC_NextGenCyber_CTF/osint.md"
              # - "Forensics": "writeups/SADC_NextGenCyber_CTF/forensics.md"
              # - "Crypto":   "writeups/SADC_NextGenCyber_CTF/crypto.md"
              # - "Pwn":      "writeups/SADC_NextGenCyber_CTF/pwn.md"
              # - "Miscellaneous": "writeups/SADC_NextGenCyber_CTF/misc.md"
              - "Boot2Root": "writeups/SADC_NextGenCyber_CTF/boot2root.md"

          - Tryhackme: 
              - "Overview": "writeups/THM_CTF/index.md"
              - "Web":      "writeups/THM_CTF/web.md"
              - "Osint":    "writeups/THM_CTF/osint.md"
              - "Forensics": "writeups/THM_CTF/forensics.md"
              - "Crypto":   "writeups/THM_CTF/crypto.md"
              - "Pwn":      "writeups/THM_CTF/pwn.md"
              - "Miscellaneous": "writeups/THM_CTF/misc.md"
  - Resources:
      - Mobile: resources/resources-for-mobile.md
      - Web: resources/resources-for-web.md
      - Pwn: resources/resources-for-pwn.md
      - Miscellaneous: resources/resources-for-misc.md
      - Osint: resources/resources-for-osint.md
      - Crypto: resources/resources-for-crypto.md
      - PrivEsc: resources/resources-for-privesc.md



theme: 
  name: material
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.tracking
    - navigation.top
    - search.share
    - search.suggest
    - search.highlight
    - toc.integrated
    - content.code.annotate
    - content.code.fold
    - content.tabs.link
    - navigation.footer
    - hero
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/favicon.ico
  extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/Fabrice000
        name: "GitHub"
      - icon: fontawesome/brands/twitter
        link: https://x.com/Dark_Carl007
        name: "Twitter"
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/carlos-fabrice-hounkpe-908498294/
        name: "LinkedIn"

markdown_extensions:
  - tables
  - attr_list
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

 
plugins:
  - search
  - git-revision-date-localized
  - social