site_name: "D4rkC4rl's Blog"
site_description: 'There is the cyber blog of D4rkC4rl.'
site_url: https://fabrice000.github.io/D4rkC4rl/

nav:
  - Home: index.md
  - Notes:
      - Learn cybersecurity: notes/article1.md
  - Write-ups:
      - CTFs: 
          - SADC: 
              - writeups/SADC NextGenCyber CTF/web.md
              - writeups/SADC NextGenCyber CTF/reversing.md
      - Tryhackme: writeups/thm.md
      - Hackthebox: writeups/htb.md
  - Resources:
      - Mobile: resources/mobile.md
      - Web: resources/web.md
      - Pwn: resources/pwn.md
      - Miscellaneous: resources/misc.md
      - Osint: resources/osint.md
      - Crypto: resources/crypto.md
  - About: about.md
  - Contact: contact.md



theme:
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/favicon.ico